name: Automated Data Fetching

on:
  push:
      branches:
      - main
      - develop

jobs:
  test_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm ci
      - run: npm run test